import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  MLSidebar: [
    {
      type: 'category',
      label: 'Designing Machine Learning Systems', // Custom name for the first group
      items: [
        { type: 'autogenerated', dirName: 'machine-learning/ml-systems' }
      ],
    },
  ],
  
  // But you can create a sidebar manually
  RLSidebar: [
    {
      type: 'category',
      label: 'Foundations on Deep Reinforcement Learning', // Custom name for the first group
      items: [
        { type: 'autogenerated', dirName: 'reinforcement-learning/foundations-drl' }
      ],
    },
    // {
    //   type: 'category',
    //   label: 'Intro to Reinforcement Learning', // Custom name for the second group
    //   items: [
    //     { type: 'autogenerated', dirName: 'reinforcement-learning/intro-to-rl' }
    //   ],
    // },
  ],

  StatsSidebar: [{type: 'autogenerated', dirName: 'statistics'}],
  
};

export default sidebars;
