            "sharing": {
                "all": ["facebook", "google", "twitter", "email", "instapaper", "github", "telegram"],
                "facebook": true,
                "facebook_link": "https://www.facebook.com/webex/",
                "google": false,
                "github": false,
                "github_link": "",
                "telegram": false,
                "instapaper": false,
                "twitter": true,
                "twitter_link": "https://twitter.com/Webex",                
                "vk": false,
                "email": true,
                "email_link": "wxcclabs@cisco.com"
            },
