            "sharing": {
                "all": ["facebook", "google", "twitter", "weibo", "instapaper", "github", "telegram", "linkedin"],
                "facebook": true,
                "facebook_link": "https://www.facebook.com/Straley/",
                "google": false,
                "github": true,
                "github_link": "https://github.com/jzstraley",
                "telegram": true,
                "telegram_link": "https://t.me",
                "instapaper": false,
                "twitter": true,
                "vk": false,
                "weibo": false,
                "linkedin": true,
                "linkedin_link": "https://www.linkedin.com/in/jamesstraley",
            },
