sequenceDiagram
    actor User
    Note over Relayer: Keepers monitor pending request
    User ->> Relayer: Request governance withdraw <br/> forward gas for relayer
    Relayer ->> Fyde: Keepers trigger <br/> processRequest
    OracleModule ->> Fyde: Return quote for withdraw
    Note over GovernanceModule: Log accounting
    Fyde ->> UserProxy: Burn TRSY
    UserProxy ->> User: Transfer asset
