sequenceDiagram
    actor User
    Note over Relayer: Keepers monitor pending request
    User ->> Relayer: Request governance deposit <br/> forward gas for relayer
    Relayer ->> Fyde: Keepers trigger <br/> processRequest
    OracleModule ->> Fyde: Return quote for deposit
    Note over Fyde: Compute process parameters <br/> (sharesToMint, tax, usdVal)
    User ->> Fyde: Transfer assets
    GovernanceModule ->> UserProxy: Create user proxy
    GovernanceModule ->> Fyde: Return user proxy
    GovernanceModule ->>  User: Mint sTRSY-assets
    Fyde ->> UserProxy: Transfer assets
    Note over Fyde: Log accounting assets
    Fyde ->> GovernanceModule: Mint TRSY
    Note over Fyde: Mint tax to Fyde
