sequenceDiagram
    actor User
    Note over Relayer: Keepers monitor pending request
    User ->> Relayer: Request standard withdraw <br/> forward gas for relayer
    Relayer ->> Fyde: Keepers trigger <br/> processRequest
    OracleModule ->> Fyde: Return quote for withdraw
    Note over Fyde: Compute process parameters <br/> (sharesToBurn, tax, usdVal)
    Fyde ->> User: Burn TRSY
    Note over Fyde: Mint tax
    Fyde ->> User: Transfer assets
    Note over Fyde: Log accounting assets
   
   
